# Generated by Django 2.1.7 on 2019-03-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('location', models.URLField()),
            ],
        ),
    ]
